[package]
name = "codewars"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ "bool_to_string", "calculate_BMI", "find_num", "fizzbuzz", "grade_book", "in_love", "min_max",
    "remove_chars", "remove_spaces", "reverse", "sum_list", "volume_cuboid",
]
